t = seq(0, 20, 0.5)
y = sin(t)
plot(t, y, type="l", xlab="time", ylab="Sine wave")

print('Diagonal matrix')
diag_matrix = diag(7, 3, 3)
print(diag_matrix)

four_d_arr =  sample(1:10, 36, replace = TRUE)
dim(four_d_arr) = c(3, 3, 2, 2)
print("4-dimension array:")
print(four_d_arr)

four_d_arr2 =  sample(1:30, 36, replace = TRUE)
dim(four_d_arr) = c(3, 3, 2, 2)

print('Mathematical operations with an array:')
print('- addition of number')
print(four_d_arr + 1)
print('- addition to another array')
print(four_d_arr + four_d_arr2)
print('- multiplication by another array')
print(four_d_arr * four_d_arr2)
print('- exponentiation')
print(four_d_arr^2)
print('- transpose')
first_part <- as.table(four_d_arr[, , 1, 1])
second_part <- as.table(four_d_arr[, , 2, 1])
third_part <- as.table(four_d_arr[, , 1, 2])
fourth_part <- as.table(four_d_arr[, , 2, 2])
print(t(first_part))
print(t(second_part))
print(t(third_part))
print(t(fourth_part))

print('3x + 2y = 8')
print('x + y = 2')
a <- matrix(c(3,1,2,1), nrow=2, ncol=2)
b <- matrix(c(8,2), nrow=2, ncol=1)
x<-solve(a, b)
print('Equation solution:')
print(x)
