print('Create a vector of 20 elements')
vec = seq(from = 1, to = 30, length.out = 20)
print(vec)
sprintf('Minimal element in vector = %.2f', min(vec))
sprintf('Maximum element in vector = %.2f', max(vec))
sprintf('Sum of elements in vector = %.2f', sum(vec))
sprintf('Vector length = %i', length(vec))
print('Randomize a vector elements')
print(sample(vec))
print('Central location of the data values = %.2f', mean(vec))
print('Sort the vector elements')
print(sort(vec))
print('Summary vector information')
multResult = prod(vec[1], vec[2], vec[3], vec[4], vec[5])
sprintf('The result of the multiplication of 5 first elements of the vector = %.2f', multResult)
print(summary(vec))